<?php

/**
 * File is auto-generated
 *
 * 131 translations-teams for WordPress found
 */
// Unhandled language: am (Amharic)
// Unhandled language: arg (Aragonese)
// Unhandled language: dsb (Lower Sorbian)
// Unhandled language: fy (Frisian)
// Unhandled language: hsb (Upper Sorbian)
// Unhandled language: kn (Kannada)
// Unhandled language: kir (Kyrgyz)
// Unhandled language: snd (Sindhi)
// Unhandled language: sw (Swahili)
return $flags = array(
	'af'             => 'za.png',
	'ar'             => 'arableague.png',
	'ary'            => 'ma.png',
	'as'             => 'in.png',
	'azb'            => 'az.png',
	'az'             => 'az.png',
	'bel'            => 'by.png',
	'bg_BG'          => 'bg.png',
	'bn_BD'          => 'bd.png',
	'bo'             => 'cn.png',
	'bs_BA'          => 'ba.png',
	'ca'             => 'catalonia.png',
	'ceb'            => 'ph.png',
	'cs_CZ'          => 'cz.png',
	'cy'             => 'wales.png',
	'da_DK'          => 'dk.png',
	'de_AT'          => 'at.png',
	'de_DE'          => 'de.png',
	'de_DE_formal'   => 'de.png',
	'de_CH'          => 'ch.png',
	'de_CH_informal' => 'ch.png',
	'dzo'            => 'bt.png',
	'el'             => 'gr.png',
	'en_ZA'          => 'za.png',
	'en_CA'          => 'ca.png',
	'en_NZ'          => 'nz.png',
	'en_GB'          => 'gb.png',
	'en_AU'          => 'au.png',
	'eo'             => 'europeanunion.png',
	'es_PE'          => 'pe.png',
	'es_CR'          => 'cr.png',
	'es_CL'          => 'cl.png',
	'es_AR'          => 'ar.png',
	'es_CO'          => 'co.png',
	'es_VE'          => 've.png',
	'es_EC'          => 'ec.png',
	'es_DO'          => 'do.png',
	'es_UY'          => 'uy.png',
	'es_PR'          => 'pr.png',
	'es_GT'          => 'gt.png',
	'es_ES'          => 'es.png',
	'es_MX'          => 'mx.png',
	'et'             => 'ee.png',
	'eu'             => 'es.png',
	'fa_AF'          => 'af.png',
	'fa_IR'          => 'ir.png',
	'fi'             => 'fi.png',
	'fr_CA'          => 'ca.png',
	'fr_FR'          => 'fr.png',
	'fr_BE'          => 'be.png',
	'fur'            => 'it.png',
	'gd'             => 'scotland.png',
	'gl_ES'          => 'es.png',
	'gu'             => 'in.png',
	'haz'            => 'af.png',
	'he_IL'          => 'il.png',
	'hi_IN'          => 'in.png',
	'hr'             => 'hr.png',
	'hu_HU'          => 'hu.png',
	'hy'             => 'am.png',
	'id_ID'          => 'id.png',
	'is_IS'          => 'is.png',
	'it_IT'          => 'it.png',
	'ja'             => 'jp.png',
	'jv_ID'          => 'id.png',
	'ka_GE'          => 'ge.png',
	'kab'            => 'dz.png',
	'kk'             => 'kz.png',
	'km'             => 'kh.png',
	'ko_KR'          => 'kr.png',
	'ckb'            => 'iq.png',
	'lo'             => 'la.png',
	'lt_LT'          => 'lt.png',
	'lv'             => 'lv.png',
	'mk_MK'          => 'mk.png',
	'ml_IN'          => 'in.png',
	'mn'             => 'mn.png',
	'mr'             => 'in.png',
	'ms_MY'          => 'my.png',
	'my_MM'          => 'mm.png',
	'nb_NO'          => 'no.png',
	'ne_NP'          => 'np.png',
	'nl_NL'          => 'nl.png',
	'nl_NL_formal'   => 'nl.png',
	'nl_BE'          => 'be.png',
	'nn_NO'          => 'no.png',
	'oci'            => 'catalonia.png',
	'pa_IN'          => 'in.png',
	'pl_PL'          => 'pl.png',
	'ps'             => 'af.png',
	'pt_BR'          => 'br.png',
	'pt_PT'          => 'pt.png',
	'pt_PT_ao90'     => '90.png',
	'pt_AO'          => 'ao.png',
	'ro_RO'          => 'ro.png',
	'ru_RU'          => 'ru.png',
	'sah'            => 'ru.png',
	'si_LK'          => 'lk.png',
	'sk_SK'          => 'sk.png',
	'skr'            => 'pk.png',
	'sl_SI'          => 'si.png',
	'sq'             => 'al.png',
	'sr_RS'          => 'rs.png',
	'sv_SE'          => 'se.png',
	'szl'            => 'pl.png',
	'ta_IN'          => 'in.png',
	'ta_LK'          => 'lk.png',
	'te'             => 'in.png',
	'th'             => 'th.png',
	'tl'             => 'ph.png',
	'tr_TR'          => 'tr.png',
	'tt_RU'          => 'ru.png',
	'tah'            => 'pf.png',
	'ug_CN'          => 'cn.png',
	'uk'             => 'ua.png',
	'ur'             => 'pk.png',
	'uz_UZ'          => 'uz.png',
	'vi'             => 'vn.png',
	'zh_CN'          => 'cn.png',
	'zh_TW'          => 'tw.png',
	'zh_HK'          => 'hk.png',
);
