<?php

/**
 * File is auto-generated
 *
 * 131 translations-teams for WordPress found
 */
// Unhandled language: am (Amharic)
// Unhandled language: arg (Aragonese)
// Unhandled language: ar (Arabic)
// Unhandled language: dsb (Lower Sorbian)
// Unhandled language: fy (Frisian)
// Unhandled language: hsb (Upper Sorbian)
// Unhandled language: kn (Kannada)
// Unhandled language: kir (Kyrgyz)
// Unhandled language: snd (Sindhi)
// Unhandled language: sw (Swahili)
return $className = array(
	'af'             => 'flag-icon-za',
	'ary'            => 'flag-icon-ma',
	'as'             => 'flag-icon-in',
	'azb'            => 'flag-icon-az',
	'az'             => 'flag-icon-az',
	'bel'            => 'flag-icon-by',
	'bg_BG'          => 'flag-icon-bg',
	'bn_BD'          => 'flag-icon-bd',
	'bo'             => 'flag-icon-cn',
	'bs_BA'          => 'flag-icon-ba',
	'ca'             => 'flag-icon-es-ca',
	'ceb'            => 'flag-icon-ph',
	'cs_CZ'          => 'flag-icon-cz',
	'cy'             => 'flag-icon-gb-wls',
	'da_DK'          => 'flag-icon-dk',
	'de_AT'          => 'flag-icon-at',
	'de_DE'          => 'flag-icon-de',
	'de_DE_formal'   => 'flag-icon-de',
	'de_CH'          => 'flag-icon-ch',
	'de_CH_informal' => 'flag-icon-ch',
	'dzo'            => 'flag-icon-bt',
	'el'             => 'flag-icon-gr',
	'en_NZ'          => 'flag-icon-nz',
	'en_ZA'          => 'flag-icon-za',
	'en_CA'          => 'flag-icon-ca',
	'en_AU'          => 'flag-icon-au',
	'en_GB'          => 'flag-icon-gb',
	'eo'             => 'flag-icon-eu',
	'es_CR'          => 'flag-icon-cr',
	'es_PE'          => 'flag-icon-pe',
	'es_CL'          => 'flag-icon-cl',
	'es_ES'          => 'flag-icon-es',
	'es_MX'          => 'flag-icon-mx',
	'es_VE'          => 'flag-icon-ve',
	'es_EC'          => 'flag-icon-ec',
	'es_DO'          => 'flag-icon-do',
	'es_UY'          => 'flag-icon-uy',
	'es_PR'          => 'flag-icon-pr',
	'es_AR'          => 'flag-icon-ar',
	'es_GT'          => 'flag-icon-gt',
	'es_CO'          => 'flag-icon-co',
	'et'             => 'flag-icon-ee',
	'eu'             => 'flag-icon-es',
	'fa_AF'          => 'flag-icon-af',
	'fa_IR'          => 'flag-icon-ir',
	'fi'             => 'flag-icon-fi',
	'fr_CA'          => 'flag-icon-ca',
	'fr_FR'          => 'flag-icon-fr',
	'fr_BE'          => 'flag-icon-be',
	'fur'            => 'flag-icon-it',
	'gd'             => 'flag-icon-gb-sct',
	'gl_ES'          => 'flag-icon-es',
	'gu'             => 'flag-icon-in',
	'haz'            => 'flag-icon-af',
	'he_IL'          => 'flag-icon-il',
	'hi_IN'          => 'flag-icon-in',
	'hr'             => 'flag-icon-hr',
	'hu_HU'          => 'flag-icon-hu',
	'hy'             => 'flag-icon-am',
	'id_ID'          => 'flag-icon-id',
	'is_IS'          => 'flag-icon-is',
	'it_IT'          => 'flag-icon-it',
	'ja'             => 'flag-icon-jp',
	'jv_ID'          => 'flag-icon-id',
	'ka_GE'          => 'flag-icon-ge',
	'kab'            => 'flag-icon-dz',
	'kk'             => 'flag-icon-kz',
	'km'             => 'flag-icon-kh',
	'ko_KR'          => 'flag-icon-kr',
	'ckb'            => 'flag-icon-iq',
	'lo'             => 'flag-icon-la',
	'lt_LT'          => 'flag-icon-lt',
	'lv'             => 'flag-icon-lv',
	'mk_MK'          => 'flag-icon-mk',
	'ml_IN'          => 'flag-icon-in',
	'mn'             => 'flag-icon-mn',
	'mr'             => 'flag-icon-in',
	'ms_MY'          => 'flag-icon-my',
	'my_MM'          => 'flag-icon-mm',
	'nb_NO'          => 'flag-icon-no',
	'ne_NP'          => 'flag-icon-np',
	'nl_NL'          => 'flag-icon-nl',
	'nl_BE'          => 'flag-icon-be',
	'nl_NL_formal'   => 'flag-icon-nl',
	'nn_NO'          => 'flag-icon-no',
	'oci'            => 'flag-icon-es-ca',
	'pa_IN'          => 'flag-icon-in',
	'pl_PL'          => 'flag-icon-pl',
	'ps'             => 'flag-icon-af',
	'pt_PT'          => 'flag-icon-pt',
	'pt_BR'          => 'flag-icon-br',
	'pt_AO'          => 'flag-icon-ao',
	'pt_PT_ao90'     => 'flag-icon-90',
	'ro_RO'          => 'flag-icon-ro',
	'ru_RU'          => 'flag-icon-ru',
	'sah'            => 'flag-icon-ru',
	'si_LK'          => 'flag-icon-lk',
	'sk_SK'          => 'flag-icon-sk',
	'skr'            => 'flag-icon-pk',
	'sl_SI'          => 'flag-icon-si',
	'sq'             => 'flag-icon-al',
	'sr_RS'          => 'flag-icon-rs',
	'sv_SE'          => 'flag-icon-se',
	'szl'            => 'flag-icon-pl',
	'ta_IN'          => 'flag-icon-in',
	'ta_LK'          => 'flag-icon-lk',
	'te'             => 'flag-icon-in',
	'th'             => 'flag-icon-th',
	'tl'             => 'flag-icon-ph',
	'tr_TR'          => 'flag-icon-tr',
	'tt_RU'          => 'flag-icon-ru',
	'tah'            => 'flag-icon-pf',
	'ug_CN'          => 'flag-icon-cn',
	'uk'             => 'flag-icon-ua',
	'ur'             => 'flag-icon-pk',
	'uz_UZ'          => 'flag-icon-uz',
	'vi'             => 'flag-icon-vn',
	'zh_TW'          => 'flag-icon-tw',
	'zh_HK'          => 'flag-icon-hk',
	'zh_CN'          => 'flag-icon-cn',
);
